version: '3'

services:
  nginx:
    image: nginx
    ports:
      - "8080:80"
    volumes:
      - ./laravel:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
  php:
    build:
      context: ./laravel
      dockerfile: Dockerfile
    volumes:
      - ./laravel:/var/www/html
    ports:
      - "9000:9000"
    # depends_on:
    #   - mysql
    command: php artisan serve --host=0.0.0.0 --port=9000
  # mysql:
  #   image: mysql:8.0.29-oracle
  #   ports:
  #     - "3307:3306"
  #   # volumes:
  #   #   - ./mysql:/var/lib/mysql
  #   environment: 
  #     MYSQL_DATABASE: laravel
  #     MYSQL_USER: dbuser
  #     MYSQL_PASSWORD: dbuser
  #     MYSQL_ROOT_PASSWORD: dbuser123
  # rabbitmq:
  #   image: rabbitmq:3-management
  #   hostname: 'rabbitmq'
  #   container_name: 'rabbitmq'
  #   ports:
  #     - 5672:5672
  #     - 15672:15672
  #   environment:
  #     - RABBITMQ_DEFAULT_USER=guest
  #     - RABBITMQ_DEFAULT_PASS=guest
    # volumes:
    #   - ./data/:/var/lib/rabbitmq/
    #   - ./log/:/var/log/rabbitmq

volumes:
  data:
  mysql:
  log: